# Generated by Django 5.0 on 2025-04-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(default='15b gandhi nagar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='classes_attended',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default='18-08-2004'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='student@eduverse.org', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='total_classes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
