# Generated by Django 5.0 on 2025-03-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffName', models.CharField(max_length=100)),
                ('staffId', models.CharField(max_length=20, unique=True)),
                ('staffEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
