# Generated by Django 5.0 on 2025-03-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_faculty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
