# Generated by Django 5.0 on 2025-04-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='age',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(default='default@eduverser.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phone',
            field=models.CharField(blank=True, default='0000000000', max_length=15),
            preserve_default=False,
        ),
    ]
