# Generated by Django 5.0 on 2025-04-17 13:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        ('students', '0005_alter_attendance_date_alter_attendance_is_present_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.CharField(default='2000-01-01', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='roll_number',
            field=models.CharField(default='2000-01-01', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='username',
            field=models.CharField(default=datetime.date(2025, 4, 17), max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='FacultyIncharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.class')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('period', models.IntegerField(choices=[(1, 'Period 1'), (2, 'Period 2'), (3, 'Period 3'), (4, 'Period 4'), (5, 'Period 5'), (6, 'Period 6'), (7, 'Period 7'), (8, 'Period 8')])),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.class')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('period', models.IntegerField()),
                ('is_present', models.BooleanField()),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.class')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
            ],
            options={
                'unique_together': {('student', 'date', 'period')},
            },
        ),
    ]
