# Generated by Django 5.0 on 2025-03-31 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_user'),
        ('students', '0006_student_classes_attended_student_total_classes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='resources/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='students.class')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='faculty.faculty')),
            ],
        ),
    ]
