# Generated by Django 5.0 on 2025-04-17 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_department_faculty_roll_number_and_more'),
        ('students', '0005_alter_attendance_date_alter_attendance_is_present_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultytimetable',
            old_name='period',
            new_name='period_number',
        ),
        migrations.CreateModel(
            name='FacultyPeriodAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('period_number', models.PositiveIntegerField()),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.class')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
            ],
            options={
                'unique_together': {('class_group', 'day', 'period_number')},
            },
        ),
    ]
