# Generated by Django 5.0 on 2025-04-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_rename_period_facultytimetable_period_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultytimetable',
            name='day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=20),
        ),
    ]
