# Generated by Django 5.0 on 2025-04-02 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_notice'),
        ('students', '0007_student_age_student_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='staffEmail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='staffName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='posted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='staffId',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='faculty',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='class_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.class'),
        ),
    ]
